#' Burglaries, Washington DC, first six months of 2016
#'
#' A dataset containing the X and Y coordinates of burglaries, with
#' the start and end date and times of the crimes. Sourced from Open Data Washington DC
#' with start date in the first six months 2016. X, Y geometry for Washington DC is from
#' FIPS 1900 (crs 7058).
#'
#' @format A data frame with 1025 rows and 4 variables:
#' \describe{
#'   \item{X}{X coordinate of burglary location}
#'   \item{Y}{Y coordinate of burglary location}
#'   \item{StartDateTime}{Start date and time of the burglary in POSIXct format}
#'   \item{EndDateTime}{End date and time of the burglary in POSIXct format}
#' }
#' @source \url{https://opendata.dc.gov/}
"dcburglaries"


#' Summary output from aoristic analysis of DC burglaries
#'
#' A dataset containing the summarized output generated by aoristic.summary() 
#' on the data frame produced by the aoristic function aoristic.df(dcburglaries, ...).
#'
#' @format A data frame with 24 observations and 8 variables:
#' \describe{
#'   \item{Range}{The hour represented by the column, in 24 hour format}
#'   \item{Mon}{Sum of aoristic values for Mondays by hour}
#'   \item{Tue}{Sum of aoristic values for Tuesdays by hour}
#'   \item{Wed}{Sum of aoristic values for Wednesdays by hour}
#'   \item{Thu}{Sum of aoristic values for Thursdays by hour}
#'   \item{Fri}{Sum of aoristic values for Fridays by hour}
#'   \item{Sat}{Sum of aoristic values for Saturdays by hour}
#'   \item{Sun}{Sum of aoristic values for Sundays by hour}
#' }
"dcburgsum"

#' Robberies, Manhattan, (New York), 2019
#'
#' A dataset containing felony robberies in Manhattan Borough, New York City with a start
#' or event date in 2019. Also contains coordinates in X, Y format using New York State Plane
#' Coordinate System, Long Island Zone, NAD 83, units feet (FIPS 3104). The data also include 
#' midblock Latitude and longitude coordinates in WGS 1984, decimal degrees (EPSG 4326). 
#' Original source data contained 35 fields. This is a filtered dataset.  


#' @format A data frame with 3089 rows and 10 variables:
#' \describe{
#'   \item{CMPLNT_FR_DT}{Exact date of occurrence for the reported event (or starting date of occurrence, if CMPLNT_TO_DT exists)}
#'   \item{CMPLNT_FR_TM}{Exact time of occurrence for the reported event (or starting time of occurrence, if CMPLNT_TO_TM exists)}
#'   \item{CMPLNT_TO_DT}{Ending date of occurrence for the reported event, if exact time of occurrence is unknown}
#'   \item{CMPLNT_TO_TM}{Ending time of occurrence for the reported event, if exact time of occurrence is unknown}
#'   \item{X_COORD_CD}{X-coordinate for New York State Plane Coordinate System, Long Island Zone, NAD 83, units feet (FIPS 3104)}
#'   \item{Y_COORD_CD}{Y-coordinate for New York State Plane Coordinate System, Long Island Zone, NAD 83, units feet (FIPS 3104)}
#'   \item{Latitude}{Midblock Latitude coordinate for Global Coordinate System, WGS 1984, decimal degrees (EPSG 4326)}
#'   \item{Longitude}{Midblock Longitude coordinate for Global Coordinate System, WGS 1984, decimal degrees (EPSG 4326)}
#'   \item{STARTDateTime}{Start date and time of the burglary in POSIXct format}
#'   \item{ENDDateTime}{End date and time of the burglary in POSIXct format}
#' }
#' @source \url{https://data.cityofnewyork.us/Public-Safety/NYPD-Complaint-Data-Current-Year-To-Date-/5uac-w243/data}
"nyrobbery"
